# syntax=docker/dockerfile:1
#
# Release image of the CMS. Build: docker build -t feather .
#
# Volumes: /data (SQLite database and image storage) and /static (staging
# sites, served by Caddy as /static/{host}, see ops/Caddyfile).
# The container migrates the database on start (bin/server).

ARG ELIXIR_VERSION=1.19.6
ARG OTP_VERSION=28.5.0.7
ARG DEBIAN_VERSION=trixie-20261005-slim

ARG BUILDER_IMAGE="docker.io/hexpm/elixir:${ELIXIR_VERSION}-erlang-${OTP_VERSION}-debian-${DEBIAN_VERSION}"
ARG RUNNER_IMAGE="docker.io/debian:${DEBIAN_VERSION}"

FROM ${BUILDER_IMAGE} AS builder

RUN apt-get update \
  && apt-get install -y --no-install-recommends build-essential git ca-certificates \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN mix local.hex --force && mix local.rebar --force

ENV MIX_ENV="prod"

# Dependencies first, for layer caching. vix downloads its precompiled NIF
# and libvips here (priv/precompiled_libvips, linked against glibc and
# libstdc++ only), so no system libvips is needed at build or run time.
COPY mix.exs mix.lock ./
RUN mix deps.get --only $MIX_ENV
RUN mkdir config

# Compile-time config only; runtime.exs is read when the release starts.
COPY config/config.exs config/${MIX_ENV}.exs config/
RUN mix deps.compile

COPY priv priv
COPY lib lib
COPY assets assets
COPY vendor vendor

# Compile before the assets: LiveView's colocated hooks are generated by
# the compiler and bundled by esbuild.
RUN mix compile
RUN mix assets.deploy

COPY config/runtime.exs config/
COPY rel rel
RUN mix release

FROM ${RUNNER_IMAGE}

# libstdc++6: needed by vix's libvips. rclone: deployments. brotli:
# precompressed static output. sqlite3: for ops (inspecting /data/feather.db).
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    libstdc++6 openssl libncurses6 locales ca-certificates \
    rclone brotli sqlite3 \
  && rm -rf /var/lib/apt/lists/*

RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && locale-gen

ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8 \
    MIX_ENV=prod \
    PHX_SERVER=true \
    PORT=4000 \
    DATABASE_PATH=/data/feather.db \
    STORAGE_PATH=/data/storage \
    STAGING_SITES_PATH=/static \
    HOME=/app

RUN groupadd --system --gid 1000 feather \
  && useradd --system --uid 1000 --gid feather --home-dir /app --shell /bin/sh feather \
  && mkdir -p /app /data /static \
  && chown feather:feather /app /data /static

WORKDIR /app
COPY --from=builder --chown=feather:feather /app/_build/prod/rel/feather ./

USER feather

VOLUME ["/data", "/static"]
EXPOSE 4000

# bin/server runs the migrations, then starts the release.
CMD ["/app/bin/server"]
