default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USERNAME") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  host:     <%= ENV.fetch("POSTGRES_HOST") %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DEVELOPMENT_DATABASE", "meerkat_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_TEST_DATABASE", "meerkat_test") %>

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_PRODUCTION_DATABASE", "meerkat_production") %>

