default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER", 'postgres') %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", 'postgres') %>
  host:     <%= ENV.fetch("POSTGRES_HOST", 'localhost') %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DEVELOPMENT_DB", "meerkat_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_TEST_DB", "meerkat_test") %>

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "meerkat_production") %>

