service: meerkat
builder:
  arch:
    - arm64

image: ghcr.io/feather-page/cms
registry:
  server: ghcr.io
  username: shostakovich
  password:
    - KAMAL_REGISTRY_PASSWORD

servers:
  web:
    hosts:
      - 23.88.127.8
  job:
    hosts:
      - 23.88.127.8
    cmd: bundle exec good_job start

volumes:
  - /web/data/caddy/static:/static
  - /web/data/meerkat:/rails/storage

env:
 secret:
   - RAILS_MASTER_KEY
   - POSTGRES_DB
   - POSTGRES_USER
   - POSTGRES_PASSWORD
   - SMTP_ADDRESS
   - SMTP_PORT
   - SMTP_USERNAME
   - SMTP_PASSWORD
   - SECRET_KEY_BASE
   - ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY
   - ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY
   - ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT
   - STAGING_SITES_PATH
   - POSTGRES_HOST
   - RAILS_ENV
   - BASE_HOSTNAME_AND_PORT
   - HTTPS

accessories:
  caddy:
    image: caddy:2
    host: 23.88.127.8
    options:
      publish:
        - "80:80"
        - "443:443"
        - "443:443/udp"
    volumes:
      - /web/data/caddy/static:/static
      - /web/data/caddy/data:/data
      - /web/data/caddy/config:/etc/caddy

  postgres:
    image: postgres:16.0
    host: 23.88.127.8
    port: "10.0.0.3:5432:5432"
    volumes:
      - /web/data/postgres:/var/lib/postgresql/data
    env:
      secret:
        - POSTGRES_DB
        - POSTGRES_USER
        - POSTGRES_PASSWORD
