service: meerkat
image: ghcr.io/meerkat-camp/cms

servers:
  - 23.88.127.8

registry:
  server: ghcr.io
  username: shostakovich
  password:
    - KAMAL_REGISTRY_PASSWORD

web:
  hosts:
    - 23.88.127.8

job:
  hosts:
    - 23.88.127.8
  cmd: bundle exec good_job start

env:
 secret:
   - RAILS_MASTER_KEY
   - POSTGRES_DB
   - POSTGRES_USER
   - POSTGRES_PASSWORD
   - SMTP_ADDRESS
   - SMTP_PORT
   - SMTP_USERNAME
   - SMTP_PASSWORD
   - SECRET_KEY_BASE
   - ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY
   - ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY
   - ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT
   - STAGING_SITES_PATH
   - POSTGRES_HOST
   - REDIS_URL
   - RAILS_ENV
   - BASE_HOSTNAME_AND_PORT
   - HTTPS

accessories:
  caddy:
    image: caddy:2
    host: 23.88.127.8
    ports:
      - 23.88.127.8:80
      - 23.88.127.8:443
    directories:
      - static:/static
      - data:/data
      - config:/etc/caddy
  postgres:
    image: postgres:16.0
    host: 23.88.127.8
    port: 10.0.0.3:5432
    directories:
      - data:/var/lib/postgresql/data
    env:
      secret:
        - POSTGRES_DB
        - POSTGRES_USER
        - POSTGRES_PASSWORD
  redis:
    image: redis:7.0
    host: 23.88.127.8
    port: 10.0.0.3:6379
    directories:
      - data:/data
