defmodule FeatherWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :feather

  require Logger

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_feather_key",
    signing_salt: "TZR/8Xuz",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :feather,
    gzip: not code_reloading?,
    only: FeatherWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :feather
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint], log: {__MODULE__, :log_level, []}

  plug Plug.Parsers,
    # Multipart bodies may carry an image of up to 25 MB (Feather.Media.max_byte_size/0)
    # through the content API; Plug's default limit is 8 MB.
    parsers: [:urlencoded, {:multipart, length: 26_000_000}, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug :session
  plug FeatherWeb.Router

  @doc """
  The level of the request log lines (`Phoenix.Logger`). Paths that carry a
  secret token (magic link, email confirmation, invitation) are logged
  with the token replaced by `[FILTERED]`: the request line is written
  here and Phoenix only logs the response line, which has no path.
  """
  @spec log_level(Plug.Conn.t()) :: Logger.level() | false
  def log_level(%Plug.Conn{} = conn) do
    case filtered_path(conn.path_info) do
      nil ->
        :info

      # Called for the request line (no status yet) and the response line.
      path when is_nil(conn.status) ->
        Logger.info([conn.method, ?\s, path])
        false

      _path ->
        :info
    end
  end

  defp filtered_path(["users", "log-in", _token]), do: "/users/log-in/[FILTERED]"

  defp filtered_path(["users", "settings", "confirm-email", _token]),
    do: "/users/settings/confirm-email/[FILTERED]"

  defp filtered_path(["invitations", _token | rest]),
    do: Enum.join(["/invitations/[FILTERED]" | rest], "/")

  defp filtered_path(_path_info), do: nil

  @doc """
  Whether cookies get the `Secure` attribute: when the endpoint's URL uses
  https (production, see config/runtime.exs), not in dev and test.
  """
  @spec secure_cookies?() :: boolean()
  def secure_cookies?, do: config(:url)[:scheme] == "https"

  # Plug.Session with `secure` decided at runtime: the URL scheme is runtime
  # configuration, plugs are initialized at compile time in production.
  defp session(conn, _opts) do
    secure? = secure_cookies?()
    key = {__MODULE__, :session_options, secure?}

    options =
      case :persistent_term.get(key, nil) do
        nil ->
          options = Plug.Session.init(Keyword.put(@session_options, :secure, secure?))
          :persistent_term.put(key, options)
          options

        options ->
          options
      end

    Plug.Session.call(conn, options)
  end
end
