defmodule Feather.Sites.Languages do
  @moduledoc """
  The ISO 639-1 language codes a site may use, with their English names.

  Ported from the Rails `Form::LanguageSelectComponent::Codes` list, which
  also contains a few legacy codes such as `in`, `ji` and `mo`.
  """

  @languages [
    {"ab", "Abkhazian"},
    {"aa", "Afar"},
    {"af", "Afrikaans"},
    {"ak", "Akan"},
    {"sq", "Albanian"},
    {"am", "Amharic"},
    {"ar", "Arabic"},
    {"an", "Aragonese"},
    {"hy", "Armenian"},
    {"as", "Assamese"},
    {"av", "Avaric"},
    {"ae", "Avestan"},
    {"ay", "Aymara"},
    {"az", "Azerbaijani"},
    {"bm", "Bambara"},
    {"ba", "Bashkir"},
    {"eu", "Basque"},
    {"be", "Belarusian"},
    {"bn", "Bengali (Bangla)"},
    {"bh", "Bihari"},
    {"bi", "Bislama"},
    {"bs", "Bosnian"},
    {"br", "Breton"},
    {"bg", "Bulgarian"},
    {"my", "Burmese"},
    {"ca", "Catalan"},
    {"ch", "Chamorro"},
    {"ce", "Chechen"},
    {"ny", "Chichewa, Chewa, Nyanja"},
    {"zh", "Chinese"},
    {"cv", "Chuvash"},
    {"kw", "Cornish"},
    {"co", "Corsican"},
    {"cr", "Cree"},
    {"hr", "Croatian"},
    {"cs", "Czech"},
    {"da", "Danish"},
    {"dv", "Divehi, Dhivehi, Maldivian"},
    {"nl", "Dutch"},
    {"dz", "Dzongkha"},
    {"en", "English"},
    {"eo", "Esperanto"},
    {"et", "Estonian"},
    {"ee", "Ewe"},
    {"fo", "Faroese"},
    {"fj", "Fijian"},
    {"fi", "Finnish"},
    {"fr", "French"},
    {"ff", "Fula, Fulah, Pulaar, Pular"},
    {"gl", "Galician"},
    {"gd", "Gaelic (Scottish)"},
    {"gv", "Manx"},
    {"ka", "Georgian"},
    {"de", "German"},
    {"el", "Greek"},
    {"kl", "Kalaallisut, Greenlandic"},
    {"gn", "Guarani"},
    {"gu", "Gujarati"},
    {"ht", "Haitian Creole"},
    {"ha", "Hausa"},
    {"he", "Hebrew"},
    {"hz", "Herero"},
    {"hi", "Hindi"},
    {"ho", "Hiri Motu"},
    {"hu", "Hungarian"},
    {"is", "Icelandic"},
    {"io", "Ido"},
    {"ig", "Igbo"},
    {"in", "Indonesian	id,"},
    {"ia", "Interlingua"},
    {"ie", "Interlingue"},
    {"iu", "Inuktitut"},
    {"ik", "Inupiak"},
    {"ga", "Irish"},
    {"it", "Italian"},
    {"ja", "Japanese"},
    {"jv", "Javanese"},
    {"kn", "Kannada"},
    {"kr", "Kanuri"},
    {"ks", "Kashmiri"},
    {"kk", "Kazakh"},
    {"km", "Khmer"},
    {"ki", "Kikuyu"},
    {"rw", "Kinyarwanda (Rwanda)"},
    {"rn", "Kirundi"},
    {"ky", "Kyrgyz"},
    {"kv", "Komi"},
    {"kg", "Kongo"},
    {"ko", "Korean"},
    {"ku", "Kurdish"},
    {"kj", "Kwanyama"},
    {"lo", "Lao"},
    {"la", "Latin"},
    {"lv", "Latvian (Lettish)"},
    {"li", "Limburgish ( Limburger)"},
    {"ln", "Lingala"},
    {"lt", "Lithuanian"},
    {"lu", "Luga-Katanga"},
    {"lg", "Luganda, Ganda"},
    {"lb", "Luxembourgish"},
    {"mk", "Macedonian"},
    {"mg", "Malagasy"},
    {"ms", "Malay"},
    {"ml", "Malayalam"},
    {"mt", "Maltese"},
    {"mi", "Maori"},
    {"mr", "Marathi"},
    {"mh", "Marshallese"},
    {"mo", "Moldavian"},
    {"mn", "Mongolian"},
    {"na", "Nauru"},
    {"nv", "Navajo"},
    {"ng", "Ndonga"},
    {"nd", "Northern Ndebele"},
    {"ne", "Nepali"},
    {"no", "Norwegian"},
    {"nb", "Norwegian bokmål"},
    {"nn", "Norwegian nynorsk"},
    {"ii", "Sichuan Yi"},
    {"oc", "Occitan"},
    {"oj", "Ojibwe"},
    {"cu", "Old Church Slavonic, Old Bulgarian"},
    {"or", "Oriya"},
    {"om", "Oromo (Afaan Oromo)"},
    {"os", "Ossetian"},
    {"pi", "Pāli"},
    {"ps", "Pashto, Pushto"},
    {"fa", "Persian (Farsi)"},
    {"pl", "Polish"},
    {"pt", "Portuguese"},
    {"pa", "Punjabi (Eastern)"},
    {"qu", "Quechua"},
    {"rm", "Romansh"},
    {"ro", "Romanian"},
    {"ru", "Russian"},
    {"se", "Sami"},
    {"sm", "Samoan"},
    {"sg", "Sango"},
    {"sa", "Sanskrit"},
    {"sr", "Serbian"},
    {"sh", "Serbo-Croatian"},
    {"st", "Sesotho"},
    {"tn", "Setswana"},
    {"sn", "Shona"},
    {"sd", "Sindhi"},
    {"si", "Sinhalese"},
    {"ss", "Swati"},
    {"sk", "Slovak"},
    {"sl", "Slovenian"},
    {"so", "Somali"},
    {"nr", "Southern Ndebele"},
    {"es", "Spanish"},
    {"su", "Sundanese"},
    {"sw", "Swahili (Kiswahili)"},
    {"sv", "Swedish"},
    {"tl", "Tagalog"},
    {"ty", "Tahitian"},
    {"tg", "Tajik"},
    {"ta", "Tamil"},
    {"tt", "Tatar"},
    {"te", "Telugu"},
    {"th", "Thai"},
    {"bo", "Tibetan"},
    {"ti", "Tigrinya"},
    {"to", "Tonga"},
    {"ts", "Tsonga"},
    {"tr", "Turkish"},
    {"tk", "Turkmen"},
    {"tw", "Twi"},
    {"ug", "Uyghur"},
    {"uk", "Ukrainian"},
    {"ur", "Urdu"},
    {"uz", "Uzbek"},
    {"ve", "Venda"},
    {"vi", "Vietnamese"},
    {"vo", "Volapük"},
    {"wa", "Wallon"},
    {"cy", "Welsh"},
    {"wo", "Wolof"},
    {"fy", "Western Frisian"},
    {"xh", "Xhosa"},
    {"ji", "Yiddish	yi,"},
    {"yo", "Yoruba"},
    {"za", "Zhuang, Chuang"},
    {"zu", "Zulu"}
  ]

  @codes Enum.map(@languages, &elem(&1, 0))
  @names Map.new(@languages)
  @preferred ~w(en de)

  @doc "All valid language codes."
  @spec codes() :: [String.t()]
  def codes, do: @codes

  @doc "Returns true if the code is a valid language code."
  @spec valid?(term()) :: boolean()
  def valid?(code), do: code in @codes

  @doc "The English name of a language code, or the code itself if unknown."
  @spec name(String.t()) :: String.t()
  def name(code), do: Map.get(@names, code, code)

  @doc """
  Options for a select: `{name, code}` tuples. English and German come first
  and are repeated in the alphabetical list, so they are found either way.
  """
  @spec options() :: [{String.t(), String.t()}]
  def options do
    preferred = Enum.map(@preferred, &{name(&1), &1})
    preferred ++ Enum.map(@languages, fn {code, name} -> {name, code} end)
  end
end
