name: RSpec
on: [push]
jobs:
  run-rspec-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.0
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: meerkat_test
        ports:
          - 5432:5432
      redis:
        image: postgres:16.0
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: meerkat_test
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run tests
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y rclone hugo libvips
          bundle exec rails db:create
          bundle exec rails db:setup
          bundle exec rspec
          i18n-tasks health
        env:
          HTTPS: false
          BASE_HOSTNAME_AND_PORT: localhost:3000
          HEADLESS: true
          STAGING_SITES_PATH: /tmp/staging_sites
      - name: Coveralls
        uses: coverallsapp/github-action@v2
